// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProAgil.Repository.Context;

namespace ProAgil.Repository.Migrations
{
    [DbContext(typeof(ProAgilContext))]
    partial class ProAgilContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("ProAgil.Domain.Entityes.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataEvento");

                    b.Property<string>("ImgUrl");

                    b.Property<string>("Local");

                    b.Property<int>("QtdPessoas");

                    b.Property<string>("Telefone");

                    b.Property<string>("Tema");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("ProAgil.Domain.Entityes.Lote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DataFim");

                    b.Property<DateTime?>("DataInicio");

                    b.Property<int>("EventoId");

                    b.Property<Guid?>("EventoId1");

                    b.Property<string>("Nome");

                    b.Property<decimal>("Preco");

                    b.Property<int>("Quantidade");

                    b.HasKey("Id");

                    b.HasIndex("EventoId1");

                    b.ToTable("Lotes");
                });

            modelBuilder.Entity("ProAgil.Domain.Entityes.Palestrante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ImgUrl");

                    b.Property<string>("MiniCurriculo");

                    b.Property<string>("Nome");

                    b.Property<string>("Telefone");

                    b.HasKey("Id");

                    b.ToTable("Palestrantes");
                });

            modelBuilder.Entity("ProAgil.Domain.Entityes.PalestranteEvento", b =>
                {
                    b.Property<int>("EventoId");

                    b.Property<int>("PalestranteId");

                    b.Property<Guid?>("EventoId1");

                    b.Property<Guid>("Id");

                    b.Property<Guid?>("PalestranteId1");

                    b.HasKey("EventoId", "PalestranteId");

                    b.HasIndex("EventoId1");

                    b.HasIndex("PalestranteId1");

                    b.ToTable("PalestranteEventos");
                });

            modelBuilder.Entity("ProAgil.Domain.Entityes.RedeSocial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EventoId");

                    b.Property<Guid?>("EventoId1");

                    b.Property<string>("Nome");

                    b.Property<int?>("PalestranteId");

                    b.Property<Guid?>("PalestranteId1");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("EventoId1");

                    b.HasIndex("PalestranteId1");

                    b.ToTable("RedeSociais");
                });

            modelBuilder.Entity("ProAgil.Domain.Entityes.Lote", b =>
                {
                    b.HasOne("ProAgil.Domain.Entityes.Evento", "Evento")
                        .WithMany("Lotes")
                        .HasForeignKey("EventoId1");
                });

            modelBuilder.Entity("ProAgil.Domain.Entityes.PalestranteEvento", b =>
                {
                    b.HasOne("ProAgil.Domain.Entityes.Evento", "Evento")
                        .WithMany("PalestranteEventos")
                        .HasForeignKey("EventoId1");

                    b.HasOne("ProAgil.Domain.Entityes.Palestrante", "Palestrante")
                        .WithMany("PalestranteEventos")
                        .HasForeignKey("PalestranteId1");
                });

            modelBuilder.Entity("ProAgil.Domain.Entityes.RedeSocial", b =>
                {
                    b.HasOne("ProAgil.Domain.Entityes.Evento", "Evento")
                        .WithMany("RedesSociais")
                        .HasForeignKey("EventoId1");

                    b.HasOne("ProAgil.Domain.Entityes.Palestrante", "Palestrante")
                        .WithMany("RedesSociais")
                        .HasForeignKey("PalestranteId1");
                });
#pragma warning restore 612, 618
        }
    }
}
